spring.application.name=ProjectProductoDigital
server.port=17071

spring.datasource.url= jdbc:oracle:thin:@10.30.1.54:1521:XE
spring.datasource.username=DAE2026
spring.datasource.password=DAE2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#hibernate configs
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jpa.hibernate.ddl-auto= update 
